### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by Cuperino** [comment]
As you're probably aware I'm using the older 5.15 runtime instead of the current 5.15-21.08 because the current one was causing QPrompt to crash upon application start. I personally haven't been to debug this due to bug [ #2725](https://github.com/flathub/flathub/issues/2725).

I tested this new build on the same x86_64 system as last time, and it seems to work perfectly fine now. Nevertheless, when I tried launching the aarch64 build on Debian 11, I got the same crash as last time on x86_64.

**Comment by Cuperino** [comment]
The app also crashes on start when I attempt to run it on a PinePhone Pro running Manjaro ARM.

**Comment by hfiguiere** [comment]
stack trace look like https://github.com/flathub/net.rpdev.OpenTodoList/pull/32

**Comment by hfiguiere** [comment]
it worked totally fine on x86_64. Didn't test on aarch64 yet, and yes it crash on a RaspberryPi 4....

**Comment by hfiguiere** [comment]
The latest update of the runtime remove the crash. I haven't tested qprompt specifically yet beside it not crashing.

**Comment by hfiguiere** [comment]
it quits but does not crash.

**Comment by hfiguiere** [comment]
I get these messages:
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:740:9: Type PrompterPage unavailable
qrc:/PrompterPage.qml:584:5: Type PrompterView unavailable
qrc:/PrompterView.qml:53:5: Type Find unavailable
qrc:/Find.qml:36:44: Invalid property assignment: "searchBarMargin" is a read-only property
```

**Comment by Cuperino** [comment]
Thank you @hfiguiere.

All of the error messages you showed stem from this:
> qrc:/Find.qml:36:44: Invalid property assignment: "searchBarMargin" is a read-only property

Nevertheless, [line 36 of the commit used to build the Flatpak](https://github.com/Cuperino/QPrompt/blob/abf46455cf8db56583722417f34c69dee75cf75a/src/prompter/Find.qml#L36) is only defining a property as readonly in the same way all other readonly properties are defined... This property isn't written to anywhere else in the program, thus I don't see what's wrong with it.

I suspect there's a bug with the QML parser in the version of Qt used for the runtime. I've been developing QPrompt against the Qt 5 patch collection and beta KF5 libraries shipped with KDE neon Testing edition since July 2021, and don't remember ever having a problem with said line.

These are the versions of the libraries I was using back in July:
> KDE Plasma Version: 5.22.4
> KDE Frameworks Version: 5.85.0
> Qt Version: 5.15.3

KDE Frameworks Version 5.84.0 and later all work fine with QPrompt. Nevertheless, I'm fairly certain this isn't a problem with KDE Frameworks, but a problem with the commit of the Qt 5.15.3 patch collection that's in use for the runtime. KDE's Qt 5.15.3 patch collection isn't a specific version but an ever changing fork of 5.15.2 with a small selection of bug fixes ported from Qt 6. Using a more current version of the patch collection with the same KF5 libraries should fix the issue in my opinion.

**Comment by hfiguiere** [comment]
Spectral has a similar problem https://github.com/flathub/org.eu.encom.spectral/pull/5#issuecomment-1037264385

**Comment by hfiguiere** [comment]
so with the latest revision of the runtime, I could get it to work without crashing on RaspberryPi.

Let's retrigger a build.


bot, build

**Comment by Cuperino** [comment]
Works perfect! Tested on a PinePhone Pro running Manjaro KDE and on KDE neon Testing Edition.
Time to merge! Thank you for following up!

**Pull request merged**
